name: "Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Disable dry-run
        if: endsWith(github.ref, '/main') && github.event_name == 'push'
        run: echo "DISABLE_DRY_RUN=true" >> $GITHUB_ENV

      - name: Publish
        run: yarn start
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
